# Generated by Django 5.2.8 on 2025-11-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaivarity',
            name='descriptin',
            field=models.TextField(default=''),
        ),
    ]
