# Generated by Django 5.2.8 on 2025-11-07 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaivarity',
            name='name',
            field=models.CharField(max_length=400),
        ),
    ]
